name: Generate and Commit Documentation

on:
  push:
    branches:
      - main  # ajuste conforme o nome da sua branch principal

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # ajuste conforme a versão do Python que você precisa

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Instalação do pacote requests

      - name: Executar script de geração de documentação
        env:
          GOOGLEAPIKEY: ${{ secrets.GOOGLEAPIKEY }}
        run: |
          python doc-gen.py

      - name: Criar pasta com data e hora
        run: |
          current_datetime=$(date '+%Y-%m-%d_%H-%M-%S')
          mkdir documentacao-$current_datetime

      - name: Mover artefatos gerados para a pasta específica
        run: |
          mv *.md documentacao-$current_datetime/

      - name: Adicionar e commit dos artefatos gerados
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Adiciona documentação gerada em $current_datetime"

      - name: Push das mudanças de volta para o repositório
        run: |
          git push origin main
        env:
          CI: true
