name: Generate and Commit Manuals

on:
  push:
    branches:
      - main

jobs:
  generate-manuals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install requests library
        run: |
          python -m pip install requests

      - name: Verify doc-gen.py and make executable
        run: |
          if [ ! -f "doc-gen.py" ]; then
            echo "Error: doc-gen.py not found."
            exit 1
          fi
          chmod +x doc-gen.py

      - name: Run doc-gen.py to generate manuals
        env:
          GOOGLEAPIKEY: ${{ secrets.GOOGLEAPIKEY }}
          TEMA: "google cloud VCP GKE"  # Defina o tema aqui ou como uma variável de ambiente no GitHub
        run: |
          python doc-gen.py "$TEMA"

      - name: Verify generated artifacts
        run: |
          ls -R

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Generated manuals for $TEMA"

      - name: Push changes back to repository
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
