name: Generate and Commit Documentation

on:
  push:
    branches:
      - main  # ajuste conforme o nome da sua branch principal

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    container:
      image: python:3.11  # imagem Docker com Python 3.11
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run doc-gen.py script
        env:
          GOOGLEAPIKEY: ${{ secrets.GOOGLEAPIKEY }}
          TEMA: "Tema para os manuais"  # Defina o tema aqui
        run: |
          python /github/workspace/doc-gen.py "$TEMA"

      - name: List generated files
        run: |
          ls -l

      - name: Add and commit generated files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Add generated documentation"
          git push origin main
